USE DATABASE COYOTE_DB;
USE WAREHOUSE COYOTE_WH;

--Vytvorenie schémy pre projekt
CREATE SCHEMA IF NOT EXISTS coyote_db.zaverecny_projekt;
USE SCHEMA coyote_db.zaverecny_projekt;

SELECT * FROM SALES_AND_INVENTORY_DATA_FOR_RETAIL_BUSINESS_INTELLIGENCE.PUBLIC.activity LIMIT 10;
SELECT * FROM SALES_AND_INVENTORY_DATA_FOR_RETAIL_BUSINESS_INTELLIGENCE.PUBLIC.item LIMIT 10;
SELECT * FROM SALES_AND_INVENTORY_DATA_FOR_RETAIL_BUSINESS_INTELLIGENCE.PUBLIC.location LIMIT 10;
SELECT * FROM SALES_AND_INVENTORY_DATA_FOR_RETAIL_BUSINESS_INTELLIGENCE.PUBLIC.retailer_metadata LIMIT 10;

--Vytvorenie staging tabuľky activity
CREATE OR REPLACE TABLE activity_staging AS 
SELECT 
    SPS_CUSTOMER_ITEM_KEY,
    SPS_RETAILER_NAME_KEY,
    SPS_CUSTOMER_LOCATION_KEY,
    SPS_ITEM_MAPPING_KEY,
    PERIOD_ENDING_DATE,
    NET_SALES_UNITS,
    NET_SALES_RETAIL,
    INVENTORY_UNITS,
    ON_ORDER_UNITS,
    RECEIPT_UNITS,
    IN_TRANSIT_UNITS,
    CORPORATE_UNIT_ADJUSTED_COST,
    CORPORATE_UNIT_ACQUIRED_COST,
    CORPORATE_UNIT_OWNED_RETAIL_PRICE
FROM SALES_AND_INVENTORY_DATA_FOR_RETAIL_BUSINESS_INTELLIGENCE.PUBLIC.ACTIVITY;

--Vytvorenie staging tabuľky item
CREATE OR REPLACE TABLE item_staging AS 
SELECT 
    SPS_RETAILER_NAME_KEY,
    SPS_CUSTOMER_ITEM_KEY,
    SPS_ITEM_MAPPING_KEY,
    CATEGORY_NAME,
    PRODUCT_GROUP_NAME,
    GENDER,
    STYLE_NUMBER,
    STYLE_DESCRIPTION,
    COLOR_NAME,
    SIZE_NAME,
    UPC,
    MSRP,
    COST,
    SPS_ITEM_STATUS
FROM SALES_AND_INVENTORY_DATA_FOR_RETAIL_BUSINESS_INTELLIGENCE.PUBLIC.ITEM;

--Vytvorenie staging tabuľky location
CREATE OR REPLACE TABLE location_staging AS 
SELECT 
    SPS_RETAILER_NAME_KEY,
    SPS_CUSTOMER_LOCATION_KEY,
    RETAILER_NAME,
    STORE_NUMBER,
    STORE_NAME,
    CITY,
    STATE,
    POSTAL_CODE,
    MALL,
    SPS_LOCATION_TYPE,
    SPS_COUNTRY_CODE,
    SPS_COUNTRY,
    SPS_LATITUDE,
    SPS_LONGITUDE
FROM SALES_AND_INVENTORY_DATA_FOR_RETAIL_BUSINESS_INTELLIGENCE.PUBLIC.LOCATION;

--Vytvorenie staging tabuľky retailer
CREATE OR REPLACE TABLE retailer_staging AS 
SELECT 
    SPS_RETAILER_NAME_KEY,
    ACTIVITYGRAIN
FROM SALES_AND_INVENTORY_DATA_FOR_RETAIL_BUSINESS_INTELLIGENCE.PUBLIC.RETAILER_METADATA;


SELECT * FROM activity_staging LIMIT 10;
SELECT * FROM item_staging LIMIT 10;
SELECT * FROM location_staging LIMIT 10;
SELECT * FROM retailer_staging LIMIT 10;
